import { Graph } from "../Graph"


/**
 * Takes a graph and collapses any arguments that are obvious.
 */
export class Interpreter {
    public constructor (config: InterpreterSettings) {
        this.config = config
    }

    /**
     * Adds "skip" nodes to the graph that skip over
     * arguments made from the given rules.
     * @param graph 
     */
    public process(graph: Graph) {
        
    }


    private readonly config: InterpreterSettings
}

export interface InterpreterSettings {
    /**
     * Set of rule ids. Arguments generated by these rules
     * will be bridged over in the graph.
     */
    skips: String[]
}